### ISSUE TITLE
OpCode Error on Spark

### ISSUE THREAD

**Issue by ahmadnazeri** [featureform/featureform#1078]
```[tasklist]
### Tasks
- [x] Figure out if Marshal works across versions
- [x] If yes, implement Marshal within Featureform
- [x] If not, throw a better error when faced with OpCode errors
- [ ] Get PR Merged
```

**Comment by ahmadnazeri** [comment]
Marshal failed at serializing the function

Transformations: 

```
def check_for_low_sugar(df):
    df["low_sugar_rate"] = (df.loc[:, "sugar_flow_rate"] < 5).astype(int)
    return df

```

The error message
```
ValueError: unmarshallable object
```

Next step would be to serve better error messages.

**Comment by ahmadnazeri** [comment]
Created a PR with the exception check when the code is being executed rather than loaded by dill. Need the PR reviewed and merged.
